In [1]:
print('hello world')

hello world


In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
hrt_df = pd.read_csv('heart.csv')
hrt_df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
hrt_df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [5]:
hrt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


## will change the nominal values into categortical values

In [6]:
hrt_df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [7]:
np.unique(hrt_df['ChestPainType'])

array(['ASY', 'ATA', 'NAP', 'TA'], dtype=object)

In [8]:
np.unique(hrt_df['RestingECG'])

array(['LVH', 'Normal', 'ST'], dtype=object)

In [9]:
np.unique(hrt_df['ExerciseAngina'])

array(['N', 'Y'], dtype=object)

In [10]:
np.unique(hrt_df['ST_Slope'])

array(['Down', 'Flat', 'Up'], dtype=object)

## lets recode these variables

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
le

LabelEncoder()

In [13]:
hrt_df['ChestPainType'] = le.fit_transform(hrt_df.ChestPainType)
hrt_df.head()

Age Sex  ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40   M              1        140          289          0     Normal   
1   49   F              2        160          180          0     Normal   
2   37   M              1        130          283          0         ST   
3   48   F              0        138          214          0     Normal   
4   54   M              2        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

In [14]:
hrt_df['RestingECG'] = le.fit_transform(hrt_df['RestingECG'])
hrt_df.head()

Age Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M              1        140          289          0           1   
1   49   F              2        160          180          0           1   
2   37   M              1        130          283          0           2   
3   48   F              0        138          214          0           1   
4   54   M              2        150          195          0           1   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

In [15]:
hrt_df['ExerciseAngina'] = le.fit_transform(hrt_df['ExerciseAngina'])
hrt_df.head()

Age Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M              1        140          289          0           1   
1   49   F              2        160          180          0           1   
2   37   M              1        130          283          0           2   
3   48   F              0        138          214          0           1   
4   54   M              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172               0      0.0       Up             0  
1    156               0      1.0     Flat             1  
2     98               0      0.0       Up             0  
3    108               1      1.5     Flat             1  
4    122               0      0.0       Up             0

In [16]:
hrt_df['ST_Slope'] = le.fit_transform(hrt_df['ST_Slope'])
hrt_df.head()

Age Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M              1        140          289          0           1   
1   49   F              2        160          180          0           1   
2   37   M              1        130          283          0           2   
3   48   F              0        138          214          0           1   
4   54   M              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [17]:
hrt_df['Sex'] = le.fit_transform(hrt_df['Sex'])
hrt_df.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

## now every nominal value is changed lets head to removing outliers

In [18]:
from scipy.stats import zscore

In [19]:
z_scores = zscore(hrt_df)

In [20]:
outliers = np.where(np.abs(z_scores)>3)
outliers

(array([ 76, 109, 149, 166, 241, 324, 365, 390, 399, 449, 592, 616, 702,
        732, 759, 771, 791, 850, 900], dtype=int64),
 array([4, 3, 4, 9, 3, 9, 3, 7, 3, 3, 3, 4, 9, 3, 3, 9, 9, 9, 9],
       dtype=int64))

In [21]:
df = hrt_df.drop(outliers[0])

In [22]:
df= hrt_df.drop(outliers[1])

In [23]:
df.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
5   39    1              2        120          339          0           1   
6   45    0              1        130          237          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
5    170               0      0.0         2             0  
6    170               0      0.0         2             0

In [24]:
df.shape

(914, 12)

In [25]:
hrt_df.shape

(918, 12)

## you see the outliers has been removed

## lets split data into training and testing

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
inputs = df.drop(['HeartDisease'],axis='columns')
target = df.HeartDisease

## before that lets scale the model

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scale = StandardScaler()

In [30]:
inputs_scaled = scale.fit_transform(inputs)
inputs_scaled

array([[-1.43171533,  0.51398156,  0.22983319, ..., -0.82471029,
        -0.83381239,  1.05473226],
       [-0.47878303, -1.94559511,  1.27494532, ..., -0.82471029,
         0.10347026, -0.59317421],
       [-1.74935943,  0.51398156,  0.22983319, ..., -0.82471029,
        -0.83381239,  1.05473226],
       ...,
       [ 0.3682679 ,  0.51398156, -0.81527893, ...,  1.21254702,
         0.29092679, -0.59317421],
       [ 0.3682679 , -1.94559511,  0.22983319, ..., -0.82471029,
        -0.83381239, -0.59317421],
       [-1.64347806,  0.51398156,  1.27494532, ..., -0.82471029,
        -0.83381239,  1.05473226]])

In [31]:
X_train,X_test,y_train,y_test = train_test_split(inputs_scaled,target,test_size=0.3)

In [32]:
len(X_train)

639

In [33]:
len(X_test)

275

## lets make the model

In [34]:
from sklearn.svm import SVC

In [35]:
model = SVC()
model

SVC()

In [36]:
model.fit(X_train,y_train)

SVC()

In [37]:
model.score(X_test,y_test)

0.8581818181818182

## hence we got this score

## now will use PCA to reduce the dimensions/features

In [38]:
from sklearn.decomposition import PCA

In [39]:
pca = PCA(0.95)
pca

PCA(n_components=0.95)

In [40]:
inputs_pca = pca.fit_transform(inputs)
inputs_pca

array([[ 92.42914516, -29.37762822],
       [-17.02334694, -13.70432695],
       [ 82.00742043,  38.28109436],
       ...,
       [-68.89579818,  17.38734805],
       [ 39.3262238 , -33.5251027 ],
       [-21.31706034, -37.18079942]])

## lets again use the new model

In [61]:
X_train,X_test,y_train,y_test = train_test_split(inputs_pca,target,test_size=0.3)

In [62]:
model = SVC()
model

SVC()

In [63]:
model.fit(X_train,y_train)

SVC()

In [64]:
model.score(X_test,y_test)

0.72

## As you can see after reducing dimesnions we saw a decrease in the accuracy of the model.